/**
 * Scaffolding file used to store all the setups needed to run
 * tests automatically generated by EvoSuite
 * Thu Dec 07 18:22:40 GMT 2017
 */

package pl.socketbyte.opengui;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@EvoSuiteClassExclude
public class ColorUtil_ESTest_scaffolding {

    private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone();
    @org.junit.Rule
    public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();
    private org.evosuite.runtime.thread.ThreadStopper threadStopper = new org.evosuite.runtime.thread.ThreadStopper(org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


    @BeforeClass
    public static void initEvoSuiteFramework() {
        org.evosuite.runtime.RuntimeSettings.className = "pl.socketbyte.opengui.ColorUtil";
        org.evosuite.runtime.GuiSupport.initialize();
        org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
        org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
        org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
        org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
        org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
        org.evosuite.runtime.classhandling.JDKClassResetter.init();
        setSystemProperties();
        initializeClasses();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    }

    @AfterClass
    public static void clearEvoSuiteFramework() {
        Sandbox.resetDefaultSecurityManager();
        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    }

    public static void setSystemProperties() {

        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
        java.lang.System.setProperty("file.encoding", "Cp1250");
        java.lang.System.setProperty("java.awt.headless", "true");
        java.lang.System.setProperty("user.country", "PL");
        java.lang.System.setProperty("user.language", "pl");
        java.lang.System.setProperty("user.timezone", "Europe/Belgrade");
    }

    private static void initializeClasses() {
        org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ColorUtil_ESTest_scaffolding.class.getClassLoader(),
                "com.google.common.base.Joiner$1",
                "com.google.common.base.Joiner$2",
                "com.google.common.collect.Multiset",
                "org.bukkit.ChatColor$19",
                "pl.socketbyte.opengui.ColorUtil",
                "org.bukkit.ChatColor$18",
                "com.google.common.collect.ImmutableEnumMap",
                "org.bukkit.ChatColor$17",
                "org.bukkit.ChatColor$16",
                "com.google.common.collect.Collections2",
                "org.bukkit.ChatColor$15",
                "org.bukkit.ChatColor$14",
                "org.bukkit.ChatColor$13",
                "org.bukkit.ChatColor$12",
                "org.bukkit.ChatColor$22",
                "org.bukkit.ChatColor$21",
                "org.bukkit.ChatColor$20",
                "com.google.common.base.Converter",
                "org.bukkit.ChatColor$6",
                "org.bukkit.ChatColor$5",
                "com.google.common.collect.BiMap",
                "org.bukkit.ChatColor$4",
                "com.google.common.collect.Maps$6",
                "org.bukkit.ChatColor$3",
                "com.google.common.base.Function",
                "org.bukkit.ChatColor$2",
                "org.bukkit.ChatColor$1",
                "com.google.common.collect.Maps$BiMapConverter",
                "com.google.common.collect.ImmutableMap",
                "com.google.common.base.Joiner$MapJoiner",
                "org.bukkit.ChatColor$9",
                "com.google.common.collect.Maps",
                "org.bukkit.ChatColor$8",
                "com.google.common.collect.SortedMapDifference",
                "org.bukkit.ChatColor$7",
                "org.bukkit.ChatColor$11",
                "org.bukkit.ChatColor$10",
                "com.google.common.collect.MapDifference",
                "com.google.common.collect.ImmutableMap$IteratorBasedImmutableMap",
                "com.google.common.collect.Maps$EntryTransformer",
                "org.bukkit.ChatColor",
                "com.google.common.base.Preconditions",
                "com.google.common.collect.UnmodifiableIterator",
                "com.google.common.base.Joiner"
        );
    }

    private static void resetClasses() {
        org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ColorUtil_ESTest_scaffolding.class.getClassLoader());

        org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
                "org.bukkit.ChatColor$1",
                "org.bukkit.ChatColor$2",
                "org.bukkit.ChatColor$3",
                "org.bukkit.ChatColor$4",
                "org.bukkit.ChatColor$5",
                "org.bukkit.ChatColor$6",
                "org.bukkit.ChatColor$7",
                "org.bukkit.ChatColor$8",
                "org.bukkit.ChatColor$9",
                "org.bukkit.ChatColor$10",
                "org.bukkit.ChatColor$11",
                "org.bukkit.ChatColor$12",
                "org.bukkit.ChatColor$13",
                "org.bukkit.ChatColor$14",
                "org.bukkit.ChatColor$15",
                "org.bukkit.ChatColor$16",
                "org.bukkit.ChatColor$17",
                "org.bukkit.ChatColor$18",
                "org.bukkit.ChatColor$19",
                "org.bukkit.ChatColor$20",
                "org.bukkit.ChatColor$21",
                "org.bukkit.ChatColor$22",
                "com.google.common.collect.Collections2",
                "com.google.common.collect.Maps",
                "org.bukkit.ChatColor",
                "com.google.common.hash.BloomFilter",
                "com.google.common.hash.BloomFilterStrategies$1",
                "com.google.common.hash.BloomFilterStrategies$2",
                "com.google.common.hash.BloomFilterStrategies",
                "com.google.common.collect.Ordering",
                "com.google.common.collect.Range$RangeLexOrdering",
                "com.google.common.collect.Cut",
                "com.google.common.collect.Cut$BelowAll",
                "com.google.common.collect.Cut$AboveAll",
                "com.google.common.collect.Range",
                "com.google.common.collect.Cut$AboveValue",
                "com.google.common.math.LongMath",
                "com.google.common.math.LongMath$1",
                "com.google.common.primitives.Ints",
                "com.google.common.collect.Cut$BelowValue",
                "com.google.common.hash.Hashing",
                "com.google.common.hash.Murmur3_128HashFunction",
                "com.google.common.hash.Hashing$Murmur3_128Holder",
                "com.google.common.hash.Murmur3_128HashFunction$Murmur3_128Hasher",
                "com.google.common.hash.HashCode",
                "com.google.common.hash.HashCode$BytesHashCode",
                "com.google.common.primitives.Longs"
        );
    }

    @Before
    public void initTestCase() {
        threadStopper.storeCurrentThreads();
        threadStopper.startRecordingTime();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
        org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
        setSystemProperties();
        org.evosuite.runtime.GuiSupport.setHeadless();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
        org.evosuite.runtime.agent.InstrumentingAgent.activate();
    }

    @After
    public void doneWithTestCase() {
        threadStopper.killAndJoinClientThreads();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
        org.evosuite.runtime.classhandling.JDKClassResetter.reset();
        resetClasses();
        org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
        org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
        org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
    }
}
