/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Dec 07 18:24:00 GMT 2017
 */

package pl.socketbyte.opengui;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@EvoSuiteClassExclude
public class FinalItemJob_ESTest_scaffolding {

    private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone();
    @org.junit.Rule
    public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();
    private org.evosuite.runtime.thread.ThreadStopper threadStopper = new org.evosuite.runtime.thread.ThreadStopper(org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


    @BeforeClass
    public static void initEvoSuiteFramework() {
        org.evosuite.runtime.RuntimeSettings.className = "pl.socketbyte.opengui.FinalItemJob";
        org.evosuite.runtime.GuiSupport.initialize();
        org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
        org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
        org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
        org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
        org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
        org.evosuite.runtime.classhandling.JDKClassResetter.init();
        setSystemProperties();
        initializeClasses();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    }

    @AfterClass
    public static void clearEvoSuiteFramework() {
        Sandbox.resetDefaultSecurityManager();
        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    }

    public static void setSystemProperties() {

        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
        java.lang.System.setProperty("file.encoding", "Cp1250");
        java.lang.System.setProperty("java.awt.headless", "true");
        java.lang.System.setProperty("user.country", "PL");
        java.lang.System.setProperty("user.language", "pl");
        java.lang.System.setProperty("user.timezone", "Europe/Belgrade");
    }

    private static void initializeClasses() {
        org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(FinalItemJob_ESTest_scaffolding.class.getClassLoader(),
                "org.bukkit.event.HandlerList",
                "pl.socketbyte.opengui.GUIExtenderItem",
                "org.bukkit.entity.Damageable",
                "org.bukkit.event.Cancellable",
                "org.bukkit.event.inventory.InventoryEvent",
                "org.bukkit.entity.AnimalTamer",
                "org.bukkit.permissions.ServerOperator",
                "org.bukkit.event.Event",
                "org.bukkit.entity.Player",
                "org.bukkit.configuration.serialization.ConfigurationSerializable",
                "pl.socketbyte.opengui.FinalItemJob",
                "pl.socketbyte.opengui.event.ElementResponse",
                "pl.socketbyte.opengui.ItemBuilder",
                "org.bukkit.projectiles.ProjectileSource",
                "org.bukkit.entity.HumanEntity",
                "org.bukkit.attribute.Attributable",
                "org.bukkit.command.CommandSender",
                "org.bukkit.entity.Entity",
                "org.bukkit.permissions.Permissible",
                "org.bukkit.event.inventory.InventoryInteractEvent",
                "org.bukkit.event.inventory.InventoryClickEvent",
                "org.bukkit.entity.LivingEntity",
                "org.bukkit.OfflinePlayer",
                "org.bukkit.inventory.InventoryHolder",
                "org.bukkit.Nameable",
                "org.bukkit.plugin.messaging.PluginMessageRecipient",
                "org.bukkit.conversations.Conversable",
                "org.bukkit.event.EventPriority",
                "org.bukkit.metadata.Metadatable"
        );
    }

    private static void resetClasses() {
    }

    @Before
    public void initTestCase() {
        threadStopper.storeCurrentThreads();
        threadStopper.startRecordingTime();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
        org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
        setSystemProperties();
        org.evosuite.runtime.GuiSupport.setHeadless();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
        org.evosuite.runtime.agent.InstrumentingAgent.activate();
    }

    @After
    public void doneWithTestCase() {
        threadStopper.killAndJoinClientThreads();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
        org.evosuite.runtime.classhandling.JDKClassResetter.reset();
        resetClasses();
        org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
        org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
        org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
    }
}
