/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 07 15:52:46 GMT 2017
 */

package pl.socketbyte.opengui;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.shaded.org.mockito.Mockito.mock;
import static org.junit.Assert.assertEquals;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class FinalItemJob_ESTest extends FinalItemJob_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        GUIExtenderItem gUIExtenderItem0 = mock(GUIExtenderItem.class, new ViolatedAssumptionAnswer());
        FinalItemJob finalItemJob0 = new FinalItemJob(2471, gUIExtenderItem0);
        int int0 = finalItemJob0.getSlot();
        assertEquals(2471, int0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        FinalItemJob finalItemJob0 = new FinalItemJob(null);
        int int0 = finalItemJob0.getSlot();
        assertEquals((-1), int0);
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        FinalItemJob finalItemJob0 = new FinalItemJob(0, null);
        int int0 = finalItemJob0.getSlot();
        assertEquals(0, int0);
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        FinalItemJob finalItemJob0 = new FinalItemJob(0, null);
        finalItemJob0.getGuiExtenderItem();
        assertEquals(0, finalItemJob0.getSlot());
    }
}
