/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 07 15:44:21 GMT 2017
 */

package pl.socketbyte.opengui;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.fail;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class GUI_ESTest extends GUI_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        Rows rows0 = Rows.ONE;
        // Undeclared exception!
        try {
            GUI.createInventory(null, rows0, "");
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.bukkit.Bukkit", e);
        }
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        // Undeclared exception!
        try {
            GUI.createInventory(null, 0, "block.wood.fall");
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.bukkit.Bukkit", e);
        }
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        Rows rows0 = Rows.ONE;
        GUI gUI0 = null;
        try {
            gUI0 = new GUI(null, "", rows0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.bukkit.Bukkit", e);
        }
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        GUI gUI0 = null;
        try {
            gUI0 = new GUI(null, "/L0N*_1e[]N!PXQ");
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.bukkit.Bukkit", e);
        }
    }

    @Test(timeout = 4000)
    public void test4() throws Throwable {
        Rows rows0 = Rows.SIX;
        GUI gUI0 = null;
        try {
            gUI0 = new GUI("", rows0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.bukkit.Bukkit", e);
        }
    }

    @Test(timeout = 4000)
    public void test5() throws Throwable {
        GUI gUI0 = null;
        try {
            gUI0 = new GUI("`iQfsR#");
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.bukkit.Bukkit", e);
        }
    }
}
