/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 07 18:24:17 GMT 2017
 */

package pl.socketbyte.opengui;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import pl.socketbyte.opengui.event.ElementResponse;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class GUIElement_ESTest extends GUIElement_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test00() throws Throwable {
        GUIElement gUIElement0 = new GUIElement(459);
        int int0 = gUIElement0.getSlot();
        assertEquals(459, int0);
    }

    @Test(timeout = 4000)
    public void test01() throws Throwable {
        GUIElement gUIElement0 = new GUIElement((-48));
        int int0 = gUIElement0.getSlot();
        assertEquals((-48), int0);
    }

    @Test(timeout = 4000)
    public void test02() throws Throwable {
        GUIElement gUIElement0 = new GUIElement((-48));
        // Undeclared exception!
        try {
            gUIElement0.addElementResponse((-48), null);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("pl.socketbyte.opengui.GUIElement", e);
        }
    }

    @Test(timeout = 4000)
    public void test03() throws Throwable {
        GUIElement gUIElement0 = new GUIElement(825, true);
        boolean boolean0 = gUIElement0.isPullable();
        assertEquals(825, gUIElement0.getSlot());
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test04() throws Throwable {
        GUIElement gUIElement0 = new GUIElement(0);
        gUIElement0.isPullable();
        assertEquals(0, gUIElement0.getSlot());
    }

    @Test(timeout = 4000)
    public void test05() throws Throwable {
        GUIElement gUIElement0 = new GUIElement(0);
        int int0 = gUIElement0.getSlot();
        assertEquals(0, int0);
    }

    @Test(timeout = 4000)
    public void test06() throws Throwable {
        GUIElement gUIElement0 = new GUIElement(1536);
        String string0 = gUIElement0.toString();
        assertEquals("[1536] 0", string0);
    }

    @Test(timeout = 4000)
    public void test07() throws Throwable {
        GUIElement gUIElement0 = new GUIElement(0);
        gUIElement0.getGuiExtenderItem();
        assertEquals(0, gUIElement0.getSlot());
    }

    @Test(timeout = 4000)
    public void test08() throws Throwable {
        GUIElement gUIElement0 = new GUIElement(459);
        gUIElement0.addElementResponse(1083, false, null);
        assertEquals(459, gUIElement0.getSlot());
        assertFalse(gUIElement0.isPullable());
    }

    @Test(timeout = 4000)
    public void test09() throws Throwable {
        GUIElement gUIElement0 = new GUIElement(0);
        gUIElement0.addElementResponse(0, (ElementResponse) null);
        assertEquals(0, gUIElement0.getSlot());
        assertFalse(gUIElement0.isPullable());
    }

    @Test(timeout = 4000)
    public void test10() throws Throwable {
        GUIElement gUIElement0 = new GUIElement(0);
        gUIElement0.getElementResponse();
        assertEquals(0, gUIElement0.getSlot());
    }
}
