/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 07 18:23:05 GMT 2017
 */

package pl.socketbyte.opengui;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class GUISettings_ESTest extends GUISettings_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        GUISettings gUISettings0 = new GUISettings();
        gUISettings0.setCanEnterItems(true);
        boolean boolean0 = gUISettings0.isCanEnterItems();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        GUISettings gUISettings0 = new GUISettings();
        gUISettings0.setCanDrag(true);
        boolean boolean0 = gUISettings0.isCanDrag();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        GUISettings gUISettings0 = new GUISettings();
        boolean boolean0 = gUISettings0.isCanDrag();
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        GUISettings gUISettings0 = new GUISettings();
        boolean boolean0 = gUISettings0.isCanEnterItems();
        assertFalse(boolean0);
    }
}
