/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 07 18:22:40 GMT 2017
 */

package pl.socketbyte.opengui;

import org.bukkit.Material;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.fail;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class ItemBuilder_ESTest extends ItemBuilder_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        Material material0 = Material.GOLD_BLOCK;
        ItemBuilder itemBuilder0 = null;
        try {
            itemBuilder0 = new ItemBuilder(material0, (int) (short) (-1417), (short) 0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.bukkit.Bukkit", e);
        }
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        Material material0 = Material.COAL_ORE;
        ItemBuilder itemBuilder0 = null;
        try {
            itemBuilder0 = new ItemBuilder(material0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.bukkit.Bukkit", e);
        }
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        ItemBuilder itemBuilder0 = null;
        try {
            itemBuilder0 = new ItemBuilder();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.bukkit.Bukkit", e);
        }
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        Material material0 = Material.COBBLE_WALL;
        ItemBuilder itemBuilder0 = null;
        try {
            itemBuilder0 = new ItemBuilder(material0, 0);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.bukkit.Bukkit", e);
        }
    }

    @Test(timeout = 4000)
    public void test4() throws Throwable {
        Material material0 = Material.SUGAR_CANE;
        ItemBuilder itemBuilder0 = null;
        try {
            itemBuilder0 = new ItemBuilder(material0, (-186), 797);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.bukkit.Bukkit", e);
        }
    }
}
