/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 07 18:22:19 GMT 2017
 */

package pl.socketbyte.opengui;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class Rows_ESTest extends Rows_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        Rows[] rowsArray0 = Rows.values();
        assertNotNull(rowsArray0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        Rows rows0 = Rows.valueOf("FOUR");
        assertEquals(36, rows0.getSlots());
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        Rows rows0 = Rows.THREE;
        int int0 = rows0.getSlots();
        assertEquals(27, int0);
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        Rows rows0 = Rows.FIVE;
        int int0 = rows0.getSlots();
        assertEquals(45, int0);
    }

    @Test(timeout = 4000)
    public void test4() throws Throwable {
        Rows rows0 = Rows.THREE;
        rows0.setSlots((-55));
        assertEquals((-55), rows0.getSlots());
    }
}
