/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Dec 07 18:23:37 GMT 2017
 */

package pl.socketbyte.opengui;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@EvoSuiteClassExclude
public class SimpleGUI_ESTest_scaffolding {

    private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone();
    @org.junit.Rule
    public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();
    private org.evosuite.runtime.thread.ThreadStopper threadStopper = new org.evosuite.runtime.thread.ThreadStopper(org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


    @BeforeClass
    public static void initEvoSuiteFramework() {
        org.evosuite.runtime.RuntimeSettings.className = "pl.socketbyte.opengui.SimpleGUI";
        org.evosuite.runtime.GuiSupport.initialize();
        org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
        org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
        org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
        org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
        org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
        org.evosuite.runtime.classhandling.JDKClassResetter.init();
        setSystemProperties();
        initializeClasses();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    }

    @AfterClass
    public static void clearEvoSuiteFramework() {
        Sandbox.resetDefaultSecurityManager();
        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    }

    public static void setSystemProperties() {

        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
        java.lang.System.setProperty("file.encoding", "Cp1250");
        java.lang.System.setProperty("java.awt.headless", "true");
        java.lang.System.setProperty("user.country", "PL");
        java.lang.System.setProperty("user.language", "pl");
        java.lang.System.setProperty("user.timezone", "Europe/Belgrade");
    }

    private static void initializeClasses() {
        org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SimpleGUI_ESTest_scaffolding.class.getClassLoader(),
                "org.bukkit.event.inventory.InventoryEvent",
                "org.bukkit.command.TabCompleter",
                "org.bukkit.permissions.ServerOperator",
                "org.bukkit.ChatColor$19",
                "org.bukkit.ChatColor$18",
                "org.bukkit.event.Event",
                "org.bukkit.ChatColor$17",
                "org.bukkit.ChatColor$16",
                "pl.socketbyte.opengui.GUIExtender",
                "org.bukkit.ChatColor$15",
                "org.bukkit.ChatColor$14",
                "org.bukkit.ChatColor$13",
                "org.bukkit.ChatColor$12",
                "org.bukkit.ChatColor$22",
                "org.bukkit.ChatColor$21",
                "org.bukkit.ChatColor$20",
                "org.bukkit.boss.BarColor",
                "org.bukkit.World",
                "org.bukkit.inventory.InventoryView$Property",
                "pl.socketbyte.opengui.event.ElementResponse",
                "org.bukkit.projectiles.ProjectileSource",
                "org.bukkit.command.CommandSender",
                "org.bukkit.entity.Entity",
                "org.bukkit.advancement.Advancement",
                "org.bukkit.OfflinePlayer",
                "org.bukkit.inventory.ItemStack",
                "org.bukkit.command.TabExecutor",
                "pl.socketbyte.opengui.SimpleGUI",
                "org.bukkit.ChatColor$11",
                "org.bukkit.ChatColor$10",
                "org.bukkit.inventory.InventoryView",
                "org.bukkit.BanList$Type",
                "org.bukkit.conversations.Conversable",
                "org.bukkit.event.inventory.InventoryOpenEvent",
                "pl.socketbyte.opengui.event.WindowResponse",
                "org.bukkit.boss.BarFlag",
                "org.bukkit.event.HandlerList",
                "org.bukkit.Warning$WarningState",
                "org.bukkit.event.inventory.InventoryCloseEvent",
                "org.bukkit.Keyed",
                "org.bukkit.Server",
                "org.bukkit.plugin.ServicesManager",
                "pl.socketbyte.opengui.GUI",
                "org.bukkit.plugin.messaging.Messenger",
                "org.bukkit.scheduler.BukkitScheduler",
                "org.bukkit.event.inventory.InventoryType$SlotType",
                "org.bukkit.plugin.PluginBase",
                "org.bukkit.util.CachedServerIcon",
                "org.bukkit.inventory.InventoryHolder",
                "org.bukkit.boss.BossBar",
                "org.bukkit.event.EventPriority",
                "org.bukkit.plugin.PluginManager",
                "org.bukkit.plugin.Plugin",
                "org.bukkit.command.ConsoleCommandSender",
                "org.bukkit.help.HelpMap",
                "org.bukkit.entity.Player",
                "org.bukkit.configuration.serialization.ConfigurationSerializable",
                "org.bukkit.inventory.Inventory",
                "org.bukkit.inventory.Merchant",
                "org.bukkit.UnsafeValues",
                "org.bukkit.inventory.Recipe",
                "org.bukkit.Bukkit",
                "org.bukkit.attribute.Attributable",
                "org.bukkit.inventory.ItemFactory",
                "org.bukkit.event.inventory.InventoryInteractEvent",
                "org.bukkit.BanList",
                "org.bukkit.event.inventory.InventoryClickEvent",
                "org.bukkit.entity.LivingEntity",
                "org.bukkit.command.PluginCommand",
                "org.bukkit.plugin.java.JavaPlugin",
                "org.bukkit.Nameable",
                "org.bukkit.plugin.messaging.PluginMessageRecipient",
                "org.bukkit.command.Command",
                "org.bukkit.command.CommandException",
                "org.bukkit.event.inventory.ClickType",
                "org.bukkit.Server$Spigot",
                "org.bukkit.entity.Damageable",
                "org.bukkit.event.Cancellable",
                "org.bukkit.entity.AnimalTamer",
                "pl.socketbyte.opengui.OpenGUI",
                "org.bukkit.WorldCreator",
                "org.bukkit.GameMode",
                "org.bukkit.boss.BarStyle",
                "org.bukkit.map.MapView",
                "org.bukkit.event.Listener",
                "net.md_5.bungee.api.ChatColor",
                "org.bukkit.entity.HumanEntity",
                "org.bukkit.ChatColor$6",
                "org.bukkit.ChatColor$5",
                "org.bukkit.generator.ChunkGenerator$ChunkData",
                "org.bukkit.ChatColor$4",
                "org.bukkit.event.inventory.InventoryAction",
                "org.bukkit.ChatColor$3",
                "org.bukkit.NamespacedKey",
                "org.bukkit.event.inventory.InventoryType",
                "org.bukkit.ChatColor$2",
                "org.bukkit.scoreboard.ScoreboardManager",
                "org.bukkit.ChatColor$1",
                "org.bukkit.permissions.Permissible",
                "org.bukkit.command.PluginIdentifiableCommand",
                "org.bukkit.command.CommandExecutor",
                "org.bukkit.ChatColor$9",
                "org.bukkit.ChatColor$8",
                "org.bukkit.ChatColor$7",
                "org.bukkit.plugin.RegisteredListener",
                "pl.socketbyte.opengui.GUISettings",
                "org.bukkit.metadata.Metadatable",
                "org.bukkit.ChatColor"
        );
    }

    private static void resetClasses() {
        org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SimpleGUI_ESTest_scaffolding.class.getClassLoader());

        org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
                "org.bukkit.event.EventPriority",
                "org.bukkit.Bukkit",
                "pl.socketbyte.opengui.OpenGUI",
                "org.bukkit.ChatColor$1",
                "org.bukkit.ChatColor$2",
                "org.bukkit.ChatColor$3",
                "org.bukkit.ChatColor$4",
                "org.bukkit.ChatColor$5",
                "org.bukkit.ChatColor$6",
                "org.bukkit.ChatColor$7",
                "org.bukkit.ChatColor$8",
                "org.bukkit.ChatColor$9",
                "org.bukkit.ChatColor$10",
                "org.bukkit.ChatColor$11",
                "org.bukkit.ChatColor$12",
                "org.bukkit.ChatColor$13",
                "org.bukkit.ChatColor$14",
                "org.bukkit.ChatColor$15",
                "org.bukkit.ChatColor$16",
                "org.bukkit.ChatColor$17",
                "org.bukkit.ChatColor$18",
                "org.bukkit.ChatColor$19",
                "org.bukkit.ChatColor$20",
                "org.bukkit.ChatColor$21",
                "org.bukkit.ChatColor$22",
                "org.bukkit.ChatColor",
                "org.bukkit.event.HandlerList",
                "org.bukkit.event.inventory.InventoryEvent",
                "org.bukkit.event.inventory.InventoryClickEvent",
                "org.bukkit.inventory.InventoryView",
                "org.bukkit.event.inventory.InventoryOpenEvent",
                "org.bukkit.event.inventory.InventoryCloseEvent"
        );
    }

    @Before
    public void initTestCase() {
        threadStopper.storeCurrentThreads();
        threadStopper.startRecordingTime();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
        org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
        setSystemProperties();
        org.evosuite.runtime.GuiSupport.setHeadless();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
        org.evosuite.runtime.agent.InstrumentingAgent.activate();
    }

    @After
    public void doneWithTestCase() {
        threadStopper.killAndJoinClientThreads();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
        org.evosuite.runtime.classhandling.JDKClassResetter.reset();
        resetClasses();
        org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
        org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
        org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
    }
}
